Add and remove functionality
Olamarx/Todo-List pull request #3
Opened 2022-05-31 18:01 UTC by Olamarx

- Add the add and remove functionalities
- Used local storage
- Used class for each file.

2022-05-31 18:16 UTC, ShahierNashaat requested changes
Hi @Olamarx , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 18:18 UTC, Olamarx commented on src/modules/logicToDisplay.js
> +    }
@ShahierNashaat can you please be explicit? I don't understand what you mean.

2022-05-31 18:35 UTC, ShahierNashaat commented on src/modules/logicToDisplay.js
> +    }
You should split them into a function for editing the task and a function for deleting the task.

2022-05-31 18:38 UTC, Olamarx commented on src/modules/logicToDisplay.js
> +    }
@ShahierNashaat There is no edit function here at all sir.
I have not added the edit function.
That is a task for tomorrow.

2022-05-31 18:42 UTC, ShahierNashaat commented on src/modules/logicToDisplay.js
> +    }
![Screenshot from 2022-05-31 20-41-34](https://user-images.githubusercontent.com/33752735/171261895-428236d7-5985-402d-9089-a621fed32ed9.png)

2022-05-31 18:45 UTC, Olamarx commented on src/modules/logicToDisplay.js
> +    }
Oh!!

Thank you!

2022-05-31 22:42 UTC, zainsadaqat requested changes
# Required Changes 🔁 
# Hello @Olamarx 


You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [x] As requested by the previous Code Reviewer, Kindly add the functionality to remove an item 👍🏻   😃 
<img width="842" alt="Screen Shot 2022-06-01 at 3 43 31 AM" src="https://user-images.githubusercontent.com/83048208/171295956-c50efecd-8ecd-403d-b238-7e07e2c157ef.png">

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 01:08 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @Olamarx**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
  
-  A function for adding a new task is implemented.✔️ 
-  A function for editing task descriptions is implemented.✔️ 
-  A function for deleting a task is implemented. ✔️ 
- Deleting a task updates all remaining items' indexes, so they represent the current list order and are unique.✔️ 
- All changes to the To-Do List should be saved in local storage.✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 01:14 UTC, merged